name: premerge

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  STAGING_DOMAIN: niranken.tk
  STAGING_SUBDOMAIN: simple-travel-diary
  STAGING_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  STAGING_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.STAGING_GOOGLE_AUTH_CLIENT_ID }}
  STAGING_GOOGLE_AUTH_CLIENT_SECRET: ${{ secrets.STAGING_GOOGLE_AUTH_CLIENT_SECRET }}
  STAGING_GOOGLE_COGNITO_SECRET_ARN: ${{ secrets.STAGING_GOOGLE_COGNITO_SECRET_ARN }}

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependency
        run: yarn --cwd ./app

      - name: Run UnitTest
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn test
          working-directory: ./app
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: install

      - name: Run E2ETest
        run: yarn --cwd ./app test:e2e

      - name: Upload E2ETest Result
        uses: actions/upload-artifact@v3
        with:
          name: e2e-result
          path: |
            ./app/cypress/videos

      - name: cdk diff for staging resources
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "diff"
          cdk_args: "-c domain=${{ env.STAGING_DOMAIN }}
            -c subdomain=${{ env.STAGING_SUBDOMAIN }}
            -c accountId=${{ env.STAGING_AWS_ACCOUNT_ID }}
            -c googleClientId=${{ env.STAGING_GOOGLE_AUTH_CLIENT_ID }}
            -c googleClientSecret=${{ env.STAGING_GOOGLE_AUTH_CLIENT_SECRET }}
            -c googleCognitoSecretArn=${{ env.STAGING_GOOGLE_COGNITO_SECRET_ARN }}"
          actions_comment: true
