name: premerge

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  precheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependency
        run: yarn --cwd ./app

      - name: Run UnitTest
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: yarn test
          working-directory: ./app
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: install

      - name: Run E2ETest
        run: yarn --cwd ./app test:e2e

      - name: Upload E2ETest Result
        uses: actions/upload-artifact@v3
        with:
          name: e2e-result
          path: |
            ./app/cypress/videos