name: Build & Deploy React App on S3
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  AWS_REGION: us-east-1
  STAGING_DOMAIN: niranken.tk
  STAGING_SUBDOMAIN: simple-travel-diary
  STAGING_AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  REACT_APP_GMAP_KEY: ${{ secrets.REACT_APP_GMAP_KEY }}
  STAGING_GOOGLE_AUTH_CLIENT_ID: ${{ secrets.STAGING_GOOGLE_AUTH_CLIENT_ID }}
  STAGING_GOOGLE_AUTH_CLIENT_SECRET: ${{ secrets.STAGING_GOOGLE_AUTH_CLIENT_SECRET }}
  STAGING_USER_POOL_ID: ${{ secrets.STAGING_USER_POOL_ID }}
  STAGING_USER_POOL_CLIENT_ID: ${{ secrets.STAGING_USER_POOL_CLIENT_ID }}
  STAGING_GOOGLE_COGNITO_SECRET_NAME: ${{ secrets.STAGING_GOOGLE_COGNITO_SECRET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GenerateRandomVariable
        run: echo REACT_APP_DUMMY_TOKEN=$(echo ${RANDOM} | md5sum | head -c 20)$(date +%s) >> $GITHUB_ENV

      - name: PreBuild
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -; sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v3

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install CDK & CDK Dependency
        run: |
          npm install -g aws-cdk > /dev/null 2>&1
          yarn install
          yarn --cwd ./app
          yarn --cwd ./lambda

      - name: Build Web
        run: |
          echo REACT_APP_GMAP_KEY=$REACT_APP_GMAP_KEY > ./app/.env.staging
          echo REACT_APP_USER_POOL_ID=$STAGING_USER_POOL_ID >> ./app/.env.staging
          echo REACT_APP_USER_POOL_CLIENT_ID=$STAGING_USER_POOL_CLIENT_ID >> ./app/.env.staging
          echo REACT_APP_COGNITO_AUTH_DOMAIN=simple-travel-diary.auth.${AWS_REGION}.amazoncognito.com >> ./app/.env.staging
          echo REACT_APP_WEB_ENDPOINT=https://${STAGING_SUBDOMAIN}.${STAGING_DOMAIN} >> ./app/.env.staging
          echo REACT_APP_DUMMY_TOKEN=${REACT_APP_DUMMY_TOKEN} >> ./app/.env.staging
          yarn --cwd ./app build:staging

      - name: cdk diff
        run: >
          cdk diff 
          -c domain=${{ env.STAGING_DOMAIN }} 
          -c subdomain=${{ env.STAGING_SUBDOMAIN }}
          -c accountId=${{ env.STAGING_AWS_ACCOUNT_ID }}
          -c googleClientId=${{ env.STAGING_GOOGLE_AUTH_CLIENT_ID }}
          -c googleClientSecret=${{ env.STAGING_GOOGLE_AUTH_CLIENT_SECRET }}
          -c googleCognitoSecretName=${{ env.STAGING_GOOGLE_COGNITO_SECRET_NAME }}
          -c principalId=${{ env.REACT_APP_DUMMY_TOKEN }}

      - name: cdk deploy
        run: >
          cdk deploy --require-approval never
          -c domain=${{ env.STAGING_DOMAIN }} 
          -c subdomain=${{ env.STAGING_SUBDOMAIN }}
          -c accountId=${{ env.STAGING_AWS_ACCOUNT_ID }}
          -c googleClientId=${{ env.STAGING_GOOGLE_AUTH_CLIENT_ID }}
          -c googleClientSecret=${{ env.STAGING_GOOGLE_AUTH_CLIENT_SECRET }}
          -c googleCognitoSecretName=${{ env.STAGING_GOOGLE_COGNITO_SECRET_NAME }}
          -c principalId=${{ env.REACT_APP_DUMMY_TOKEN }}

