name: Build & Deploy React App on S3
on:
  push:
      branches:
        - main

permissions:
  id-token: write
  contents: read

env:
  AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
  AWS_REGION: us-east-1
  STAGING_DOMAIN: niranken.tk
  STAGING_SUBDOMAIN: simple-travel-diary
  STAGING_AWS_ACCOUNT_ID: $${{ secrets.AWS_ACCOUNT_ID }}
  STAGING_GMAP_API_KEY: $${{ secrets.STAGING_GMAP_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PreBuild
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -; sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v3

      - name: Assume Role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ env.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install CDK Dependency
        run: npm install

      - name: Build Web
        run: yarn --cwd ./app && echo REACT_APP_GMAP_KEY=${{ env.STAGING_GMAP_API_KEY }} > ./app/.env && yarn --cwd ./app build

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          cdk_args: '-c domain=${{ env.STAGING_DOMAIN }} -c subdomain=${{ env.STAGING_SUBDOMAIN }} -c accountId=${{ env.STAGING_AWS_ACCOUNT_ID }}'
          actions_comment: true

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never -c domain=${{ env.STAGING_DOMAIN }} -c subdomain=${{ env.STAGING_SUBDOMAIN }} -c accountId=${{ env.STAGING_AWS_ACCOUNT_ID }}'
          actions_comment: false